name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2"]
        gemfile: [
          "Gemfile"
        ]
        include:
        - ruby: "3.2"
          gemfile: "gemfiles/action_policy/master.gemfile"
        - ruby: "3.0"
          gemfile: "Gemfile"
        - ruby: "3.0"
          gemfile: "gemfiles/action_policy/master.gemfile"
        - ruby: "2.7"
          gemfile: "Gemfile"
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec tests
      run: |
        bundle exec rspec --force-color
